version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - shared-data:/path/to/shared/data
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: monmotdepasse
      MYSQL_DATABASE: mabdd
    volumes:
      - shared-data:/var/lib/mysql

volumes:
  shared-data:
